add mytftpd, and many many files

diff --git a/MK_ANDROID_RAMDISK b/MK_ANDROID_RAMDISK
--- a/MK_ANDROID_RAMDISK
+++ b/MK_ANDROID_RAMDISK
@@ -24,23 +24,25 @@ function copy_busybox()
 }
 
 # copy_busybox
-    
+
 if [ -d root ]; then
     if [ -f ramdisk.img ]; then
         echo "backup ramdisk.img to ramdisk.img.org.$Date"
         mv ramdisk.img ramdisk.img.org.$Date
-        mkbootfs root/ | minigzip > ramdisk.img
-        target=ramdisk.img
-        if is_smdkv210; then
-            mkimage -A arm -O linux -T ramdisk -C none -a 0x30800000 -n "ramdisk" -d ramdisk.img ramdisk-uboot.img
-            target=ramdisk-uboot.img
-        fi
-
-        echo "make android ramdisk [$target] ok"
-        ls -l $target
-
-        exit 0
     fi
+
+    mkbootfs root/ | minigzip > ramdisk.img || echo "mkbootfs may fail!" && exit 100
+    target=ramdisk.img
+    if is_smdkv210; then
+        mkimage -A arm -O linux -T ramdisk -C none -a 0x30800000 -n "ramdisk" -d ramdisk.img ramdisk-uboot.img
+        target=ramdisk-uboot.img
+    fi
+
+    echo "make android ramdisk [$target] ok"
+    ls -l $target
+
+    exit 0
+
 fi
 
 echo "failed to make the ramdisk!!!"
